backend:
  name: github
  repo: nolabernard/blog
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "articles"
    label: "Articles"

    files:
      - label: "Tous les articles"
        name: "articles"
        file: "content/articles.json"
        format: "json"

        fields:
          - label: "Articles"
            name: "articles"
            widget: "list"
            add_to_top: true
            summary: "{{fields.title}}"

            fields:
              - label: "Titre"
                name: "title"
                widget: "string"

              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "Exemple : pourquoi-je-change-davis"

              - label: "Catégorie"
                name: "category"
                widget: "select"
                options:
                  - "Entreprendre"
                  - "Psychologie"
                  - "Réflexions"

              - label: "Date"
                name: "date"
                widget: "datetime"
                format: "YYYY-MM-DD"
                time_format: false

              - label: "Temps de lecture"
                name: "readingTime"
                widget: "string"
                default: "5 min"

              - label: "Introduction"
                name: "intro"
                widget: "text"

              - label: "Image"
                name: "image"
                widget: "image"
                required: false

              - label: "Contenu"
                name: "body"
                widget: "markdown"
  - name: "settings"
    label: "Réglages du site"
    files:
      - label: "Maintenance"
        name: "maintenance"
        file: "content/settings.json"
        format: "json"
        fields:
          - label: "Mode maintenance"
            name: "maintenance"
            widget: "boolean"
            default: false

          - label: "Titre maintenance"
            name: "maintenanceTitle"
            widget: "string"

          - label: "Message maintenance"
            name: "maintenanceMessage"
            widget: "text"

  - name: "pages"
    label: "Pages"
    files:
      - label: "Accueil"
        name: "home"
        file: "content/home.json"
        format: "json"
        fields:
          - label: "Titre principal"
            name: "heroTitle"
            widget: "string"

          - label: "Texte d'introduction"
            name: "heroText"
            widget: "text"

          - label: "Titre de la section articles"
            name: "latestArticlesTitle"
            widget: "string"

          - label: "Texte de fin de page"
            name: "closingText"
            widget: "text"
